### ISSUE TITLE
Design research tree

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#407]

**Comment by softsound** [comment]
![image](https://user-images.githubusercontent.com/1772703/46039523-8c57d900-c0d3-11e8-9a0b-259258490807.png)

[linky](https://www.youtube.com/watch?v=QSAQ2FM7jK8)

![image](https://user-images.githubusercontent.com/1772703/46039549-9f6aa900-c0d3-11e8-9b9c-86c4e6028914.png)

![image](https://user-images.githubusercontent.com/1772703/46039572-adb8c500-c0d3-11e8-8997-23b2fceb1eae.png)

**Comment by softsound** [comment]
1) Research becomes a permanent upgrade for that campaign.
2) Research affects each ship class or all units of x ship.
3) Research tree can be upgraded in-game as you find objects (we have a menu key -- at some point, we need to just add it as a part of the pause menu.)

**Comment by josefnpat** [comment]
Taking over design locally

**Comment by josefnpat** [comment]
Current design:

![image](https://user-images.githubusercontent.com/646162/46060834-264a7080-c12a-11e8-88c6-b060e462e4af.png)

**Comment by VividReality** [comment]
I think the icons on the left will leave the user guessing what it stands for because they won't memorize every ship / icon combination. Therefore I propose the following:

![image](https://user-images.githubusercontent.com/2211930/46496476-6e4b5080-c818-11e8-9e4c-e38abee88a3f.png)
I created this mockup for what I think will make a better user experience.

Since the codebase doesn't have scrollbars yet I made an alternative
![image](https://user-images.githubusercontent.com/2211930/46496520-8a4ef200-c818-11e8-98b6-0eabce43075f.png)
