### ISSUE TITLE
Realign Menu

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#487]
Please save my sanity
![image](https://user-images.githubusercontent.com/1772703/45270457-49ef9480-b463-11e8-975a-4951903f9048.png)

![image](https://user-images.githubusercontent.com/1772703/45270560-5fb18980-b464-11e8-95f9-3a3b311b98f4.png)

![image](https://user-images.githubusercontent.com/1772703/45270601-d484c380-b464-11e8-990c-f8196643d405.png)

Not sure if this is improving
![image](https://user-images.githubusercontent.com/1772703/45270764-87095600-b466-11e8-9430-cd3e95308153.png)

**Comment by josefnpat** [comment]
Changing this will also alter other menu alignments:
![image](https://user-images.githubusercontent.com/646162/45271128-309e1680-b46a-11e8-9f3e-00edbcb2b5dc.png)

**Comment by softsound** [comment]
#417

**Comment by softsound** [comment]
#502

**Comment by josefnpat** [comment]
I have aligned the menus to be in the center as requested.

As for your concerns about spacing otherwise, menu widgets are aligned by 16ths:

![image](https://user-images.githubusercontent.com/646162/46678739-eb751d80-cbaa-11e8-9ecb-2297bda08b41.png)

![image](https://user-images.githubusercontent.com/646162/46678716-dd270180-cbaa-11e8-882a-f034a1108bd0.png)

Please tell me if this is unnaceptable, or if we can close this ticket.

**Comment by softsound** [comment]
Looking a lot better thank you!
