### ISSUE TITLE
Double clicking teammate's ships gives audio cue 

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#545]
When double clicking on teammate's ships, acknowledgement from the ship is given. I am not able to move the ship (which is correct), but the audio still plays.

_official bug report format will be posted at a later time_

**Comment by josefnpat** [comment]
So, this bug is pretty cool.

The double click feature allows you to select all the units of the same time as the unit you double clicked. The only problem is that the user of the original ship is never taken into account.

By double clicking on an enemy command ship, you essentially tell the system to select all of your command ships.
