### ISSUE TITLE
Make the voice commands less frequent

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#557]
Make the voice commands less frequent, perhaps add a randomizer that has a 30% chance to play a random voice.

It's slightly better then MegaMan telling the player Everytime he switches his weapons.

I've been reading some UX design articles and one wrote, 
"Voice announcements are cognitively expensive for the user, so only use them when the message is specific enough to overload non-verbal channels, or important enough to preclude ambiguity."

I don't think our message is really important enough and I find it annoying after a while.

https://youtu.be/XVc22bImwH0

**Comment by VividReality** [comment]
I agree to some extent, but making it random is inconsistent. If feedback for an action happens only 30% of the time then that is cognitively even more expensive, because you never know when to expect it from happening. I propose instead of making it less frequent, to add more sounds that are less cognitively expensive, like a quick "hmhm" or even just a grunt, keeps it consistent yet a lot less annoying.

**Comment by josefnpat** [comment]
I want to rebuild this so only the first sound plays, so the user doesn't get spammed with audio

**Comment by josefnpat** [comment]
sfx now dynamically load

`sfx.loopGroup` command will determine if there is an audio file being played in a group, and will not play said audio file if there is one already playing.
