### ISSUE TITLE
Main screen background

### ISSUE THREAD

**Issue by softsound** [josefnpat/roguecraft-squadron#572]
Current
![image](https://user-images.githubusercontent.com/1772703/46630515-05125880-cb0a-11e8-88b6-b5da787859e4.png)

I wanted something more sci-fi so I referenced starcraft
![image](https://user-images.githubusercontent.com/1772703/46630531-18bdbf00-cb0a-11e8-8ff5-c02a0f8d9a5c.png)

Goal
![image](https://user-images.githubusercontent.com/1772703/46630550-22dfbd80-cb0a-11e8-8dd3-432862fc4842.png)

This is what I think we should take action on.
- [ ] I want to use the in-game FOW and background. 

I think it would be fun if a random ship flew by now and then too.... But that is a different ticket. #40

**Comment by josefnpat** [comment]
Insufficient details and assets to be actionable:

1. Your fog of war also includes the full game
2. The menu buttons have changed - if it's not a part of the ticket, please remove it. If it is, pelase make a new ticket.
3. `I think it would be fun if a random ship flew by now and then too.... But that is a different ticket.` Where is this ticket? Please link to it.
4. Please provide assets so this can be implemented.

**Comment by softsound** [comment]
1. I'm not going to erase ships. Originally I wanted a video background but a FOW seems easier.
2. It's already a ticket so I'm not removing. #525 
3. #40 
4. Don't you have FOW assets?

**Comment by josefnpat** [comment]
1. There are literally no assets to use as the "background" for the menu:
  a. the background paralaxes, so it's already just three layers of tiles
  b. the ships require a gamemode to be drawn, otherwise they won't match with all the chevrons, shaders, etc. If you're asking me to implement a game mode, this is going to be very hard, and we need an easier solution.
2. Thank you - please mention that ticket if you're going to provide a mockup with it in it
3. Thank you
4. FOW assets do not work like that at all. Here's the asset: https://github.com/josefnpat/roguecraft-squadron/blob/master/src/assets/fow.png

**Comment by softsound** [comment]
Would it be easier for me to just make a video and have you play it in the background or that too much work right now? We can save this ticket for after release and go over it again.
