### ISSUE TITLE
AI stop collecting and building over time

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#602]
_Alt title: AI have no ambition to fight._

_Operating System_
Windows 10 

_Version_
Game: v842[462fc6b]
Client: v837[7af2c01]

_Repro_
1. Begin a multiplayer game. 
      Add AI (my tests have been with 2-3 AI), 
      Full Game, 
      command capacity (100-200), 
      AI levels any (tested on rage quit and no ice cream)
2. Play game normally or destroy your ships and spectate.

_Expectation_
As the game goes on, the AI gather all resources and aggressively find and destroy you or other AI.

_Result_
AI sit at their starter resource pockets, ~and have a beer~ idling and not collecting resources.

_Additional Info_
- AI still have resources to collect. It appears something is blocking them (either full on resources, hit command capacity, etc).
- Ran a test removing the new Capital Ship, to see if the AI was trying to bulid it and was causing the block. Test result shows that AI are still showing the _Result_ behavior.
- Depending on number of AI, sometimes they'll fight another AI, but afterward they become docile.

**Comment by josefnpat** [comment]
So there are ships marked as military_large (e.g. artillery, tank, battlestar). When that type of ship is prioritized the system determines the most expensive ship there is, to avoid only ever having enough resources to make the cheapest ships.

Since the Capital ship that we have is excessively expensive, it goes beyond even the capacity of an early game AI. When it checks for the most expensive military_large ship there is, it skips it because it can't afford the most expensive.

At some point, the AI finishes prioritizing military_small and more civilian based tags, and it only attempts to build military_large. Because it cannot afford the most expensive military_large, it just keeps trying, effectively in an infinite loop.

The thing that made me realize this was the fact that the AI never made any military_large ships at all.
