### ISSUE TITLE
Build Queue does not resume when enough resources are available.

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#613]
_Related to #496_

- Not currently able to Repro (no steps available)
- Repro steps will be added in the future

_Additional Notes_
The event seems to happen after the ships regain the materials to resume the building but aren't getting the signal to dequeue and resume building.

**Comment by snowschu** [comment]
This needs to be recorded and reviewed when it happens. Not enough information is available when we reports of this event happening, which is making this difficult to resolve.

When playing, please make a recording.

**Comment by josefnpat** [comment]
repro:

1. Change build_time to 0.1 in code (not creative mode)
2. Get an economy going
3. build a bunch of civ drydocks
4. select them all and mass build something cheap

a few of the civ drydocks should get messed up.

**Comment by josefnpat** [comment]
This was an interesting bug, let me explain:

The client and server sync the resources every frame, but it doesn't do it in the middle of a frame.

1. The client requests to build multiple objects in the same frame (e.g. when you select multiple ships and build). Because the resources are not decremented, the client assumes it can afford all of them.
2. The server receives the request, but can only afford a subset of the ships requested. It enques the ones it can afford, but then ignores the ones it can't afford.
3. Because the client waits on the server to inform it when the objects spawn, an object that was discarded will never spawn an object, hence locking the parent object.

This was fixed by adding a dequeue response from the server.

1. The client requests to build multiple objects in the same frame The client assumes it can afford all of them.
2. The server receives the request, but can only afford a subset of the ships requested. It enques the ones it can afford, and informs the client to dequeue objects that failed.
3. The client reads the dequeue, and puts the object back at the front of the queue, and tries one second later.
