### ISSUE TITLE
Presskit of RCS

### ISSUE THREAD

**Issue by snowschu** [josefnpat/roguecraft-squadron#623]
Related to #86 
Please use [google doc link](https://docs.google.com/document/d/15IYy-oRj2nVfElaIW5l0T2xeaR0TVVuwupSVPQuaRRw/edit?usp=sharing) provided:

- [x] A brief written early history of RCS. Roughly one paragraph
- [x] A brief written present history of RCS. Roughly one paragraph. 
_(Probably around when we did the pivot would be where ‘present history’ starts.)_
- [x] Confirm credits

**Comment by josefnpat** [comment]
Should be able to find credit information in game under credits.

https://github.com/josefnpat/roguecraft-squadron/blob/master/src/states/credits.lua#L78

**Comment by josefnpat** [comment]
I'm not sure I understand.

The current list is:

* Josef Patoprsty (@josefnpat) — Code, Art, Design, Voice Talent
* Ashley Hooper (@ByteDesigning) — Code, Art
* Ashley Schuster (SnowSchu) — Marketing and QA
* Ran Schonewille (audio-interactive.com) — Music Composer
* Noyemi Karlaite (@NoyemiK) — Character Art
* Laura Vk (Solsforest) — Art, Voice Talent
* Arjan Vk (Vivid) — Code, SFX, Voice Talent
* Ethan Blackley — Video Marketing

If we replace the marketing video, we will move ethan to a thanks section in the credits.

**Comment by softsound** [comment]
Roguecraft Squadron is a nostalgia-filled RTS. It began in 2017 as a three-day game jam and did well in the jam competition landing 3rd place. Because of its early success, we brought it to SXSW and continued showing at other events while developing it further.

In 2018 we decided a much-needed feature was multiplayer and that became a major turning point for the game. This allowed us the ability to add in co-op and vs mode with up to 8 friends in a single match. This made the game fun for everyone as people could decide their play style. And now in 2019, we will be releasing an exciting multiplayer game with the ability to play through a story or engage in fights between friends. You choose the way to the play.

**Comment by softsound** [comment]
I think we need to move Ethan to the thanks section.

**Comment by josefnpat** [comment]
We can do that once we have a new video.

**Comment by snowschu** [comment]
https://docs.google.com/document/d/128lk3CCyHjxfLU2ETNKunkapEqm4tkyJz_y5ctWHSZE/edit?usp=sharing

**Comment by snowschu** [comment]
[rcs-logo.zip](https://github.com/josefnpat/roguecraft-squadron/files/2788591/rcs-logo.zip)

**Comment by softsound** [comment]
This seems finished.

**Comment by softsound** [comment]
After reviewing the presskit some key details were missing.

I have included an FAQ and will also a small graphics package for streamers/vloggers/let's play.

I have reformatted the data and put it all in this google doc.

https://docs.google.com/document/d/1pL7ie0LSVv1nRJ_QGFyGpuHILDPw-4fVp8NrNymRCXc/edit?usp=sharing

The media kit is google drive.

**Comment by josefnpat** [comment]
blocked by #312

**Comment by softsound** [comment]
I think it's just good to include since we barely have a website anyway and I don't see the website improving anytime soon.

**Comment by josefnpat** [comment]
http://roguecraftsquadron.com/presskit/
