### ISSUE TITLE
Add Pause

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/roguecraft-squadron#707]
Add a way to pause the game.

Pause automatically on PvE games.

**Comment by snowschu** [comment]
Bumping this in relation to VN (campaign mode). Ref: #869 

When players begin `Campaign` or `LoveJam` mode, the "game" begins at the start of the cut scenes. This can be an issue, considering: 
- There will be players who want to linger and read the story
and
- we want to encourage players to read the story, rather than skip it altogether (at least their first time through)
